import React from 'react'
import { useRouter } from 'next/router';
import Head from 'next/head'
import SideBar from '../components/SideBar'
import TopBar from '../components/TopBar'
import SingleArticle from '../components/SingleArticle';
import Footer from '../components/Footer';


function Article() {
    const router = useRouter();
    console.log(router.query)
    return (
        <div>
           <Head>
        <title>Casino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col md:flex md:flex-row">
       <div className="">
       <SideBar/>
       </div>
       <div className="flex-col grow">
       <TopBar/>
       <SingleArticle single={router.query}/>
       <Footer/>
       </div>
     </div>

        </div>
    )
}

export default Article
