import React from 'react'
import Head from 'next/head'
import Landing from "../components/Landing"
import SideBar from '../components/SideBar'
import TopBar from '../components/TopBar'
import BlogArticleCard from '../components/BlogArticleCard'
import Footer from '../components/Footer'
import Articles from '../components/Articles'


function Blog() {
    return (
        <div>
           <Head>
        <title>Casino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col md:flex md:flex-row">
       <div className="">
       <SideBar/>
       </div>
       <div className="flex-col grow">
       <TopBar/>
       <BlogArticleCard/>
       <Articles/>
       </div>
     </div>

        </div>
    )
}

export default Blog
